### ISSUE TITLE
No filtra fechas en get_daily_history

### ISSUE THREAD

**Issue by fgls2020** [ggallohernandez/pymatriz#4]
[client.get_daily_history](https://github.com/ggallohernandez/pymatriz/blob/b76e45fa288efd60cf27b8d30706b03bc1b9689f/pymatriz/client.py#L41) no está tomando los parámetros _start_date_ ni _end_date_. Si ejecuto el ejemplo [pymatriz/examples/get_daily_history.py](https://github.com/ggallohernandez/pymatriz/blob/master/examples/get_daily_history.py) tengo ésta salida:

```
                                                 open  high    low  close    volume
sid                       time
MERV - XMEV - GGAL - 24hs 2017-08-22T03:00:00Z  73.60  73.6  73.20   73.2     875.0
                          2017-08-23T03:00:00Z  74.25  77.1  74.25   77.1   31716.0
                          2017-08-24T03:00:00Z  78.00  78.0  77.00   78.0    2065.0
                          2017-08-25T03:00:00Z  77.30  77.3  77.20   77.2     169.0
                          2017-08-28T03:00:00Z  77.60  78.2  77.60   78.2     375.0
...                                               ...   ...    ...    ...       ...
MERV - XMEV - SUPV - 48hs 2020-12-04T03:00:00Z  60.50  61.5  59.50   59.7  314541.0
                          2020-12-09T03:00:00Z  59.70  59.7  57.00   57.0  185281.0
                          2020-12-10T03:00:00Z  56.80  59.9  56.00   58.2  291286.0
                          2020-12-11T03:00:00Z  58.05  61.4  58.05   61.4  159476.0
                          2020-12-14T03:00:00Z  60.95  61.2  59.35   60.0  199669.0
```

Pero se está llamando la función con `start_date=datetime.date(2020, 9, 14))`

**Comment by ggallohernandez** [comment]
Gracias por el aviso, lo voy a revisar!

**Comment by chepalitos** [comment]
Me estaría dando un error, creo no estar haciendo las cosas mal. Tal vez lo estés revisando aún. Es con el mismo ejemplo.
```[797 rows x 5 columns]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/chepalitos/.local/lib/python3.9/site-packages/websocket/_app.py", line 306, in run_forever
    dispatcher.read(self.sock.sock, read, check)
  File "/home/chepalitos/.local/lib/python3.9/site-packages/websocket/_app.py", line 66, in read
    if not read_callback():
  File "/home/chepalitos/.local/lib/python3.9/site-packages/websocket/_app.py", line 270, in read
    return teardown()
  File "/home/chepalitos/.local/lib/python3.9/site-packages/websocket/_app.py", line 231, in teardown
    if thread and thread.isAlive():
AttributeError: 'Thread' object has no attribute 'isAlive'
